mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_delete'),

    # Path for streaming picture
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    # Paths for comments
    path('ad/<int:pk>/comment/create',
        views.CommentCreateView.as_view(),
        name='comment_create'),
    path('ad/comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(),
        name='comment_delete'),

    # Paths for favorite/ unfavorite
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'),
]

mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'

urlpatterns = [
    path('', views.CatListView.as_view(), name='all'),
    path('cat/create/', views.CatCreateView.as_view(), name='cat_create'),
    path('cat/<int:pk>/update/', views.CatUpdateView.as_view(), name='cat_update'),
    path('cat/<int:pk>/delete/', views.CatDeleteView.as_view(), name='cat_delete'),

    path('breed/', views.BreedListView.as_view(), name='breed'),
    path('breed/create/', views.BreedCreateView.as_view(), name='breed_create'),
    path('breed/<int:pk>/update/', views.BreedUpdateView.as_view(), name='breed_update'),
    path('breed/<int:pk>/delete/', views.BreedDeleteView.as_view(), name='breed_delete'),

    path('cats_refresh', views.cats_refresh, name='refresh'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView
from hello import views as hv

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # admin app
    path('admin/', admin.site.urls),

    # apps home page
    path('', TemplateView.as_view(template_name='home/main.html'), name='home'),

    # Guess Game by Chornenkj
    path('guess/', include('guess.urls')),

    #Ads app to pass DJ4E module on Owned Rows and Users` permittions
    path('ads/', include('ads.urls')),

    # Autos CRUD app to pass course DJ4E module
    # on creating, retreaving, updating and deleting forms
    path('autos/', include('autos.urls')),

    # Cats app to pass course DJ4E module
    # on creating a database
    path('cats/', include('cats.urls')),

    # Unesco app to create database from csv-file
    path('unesco/', include('unesco.urls')),

    # URLs for login and logout
    path('accounts/', include('django.contrib.auth.urls')),

    # these two apps are created just to pass course DJ4E
    path('polls/', include('polls.urls')),
    path('hello/', hv.myview, name='hello'),

    # this is just to browse files in the course DJ4E
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Cat, Breed
from scripts import cats

# Create your views here.

class CatListView(LoginRequiredMixin, ListView):
    model = Cat

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breeds_count'] = Breed.objects.all().count()
        return context

class CatCreateView(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdateView(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatDeleteView(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedListView(LoginRequiredMixin, ListView):
    model = Breed

class BreedCreateView(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedUpdateView(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedDeleteView(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

def cats_refresh(request):
    cats.refresh()
    return HttpResponseRedirect(reverse('cats:all'))

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>Delete a Breed</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form|crispy }}
    <br/>
    <input type="submit" class="btn btn-primary" value="Yes, delete.">
    <input type="submit" class="btn btn-secondary"
        onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>Your Breed</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br/>
    <input type="submit" class="btn btn-primary" value="Submit">
    <input type="submit" class="btn btn-secondary"
        onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>List of Breeds</h1>

<ul>
    {% for item in object_list %}
        <li>{{ item }} (<a href="{% url 'cats:breed_update' item.id %}">Update</a> | <a
            href="{% url 'cats:breed_delete' item.id %}">Delete</a>)</li>
    {% empty %}
        <p>There is no breeds yet.</p>
    {% endfor %}
</ul>

<p><a class="btn btn-primary" href="{% url 'cats:breed_create' %}">Add a Breed</a></p>

<p><a href="{% url 'cats:all' %}">Back to Cats</a></p>

{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>Delete a Cat</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form|crispy }}
    <br/>
    <input type="submit" class="btn btn-primary" value="Yes, delete.">
    <input type="submit" class="btn btn-secondary"
        onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>Your Cat</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br/>
    <input type="submit" class="btn btn-primary" value="Submit">
    <input type="submit"class="btn btn-secondary"
        onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block title %}
Cats CRUD
{% endblock %}

{% block content %}
<h1>List of Cats</h1>

<ul>
    {% for item in object_list %}
        <li>{{ item }} ({{ item.breed }}) (<a
            href="{% url 'cats:cat_update' item.id %}">Update</a> | <a
            href="{% url 'cats:cat_delete' item.id %}">Delete</a>)</li>
    {% empty %}
        <p>There is no cats yet.</p>
    {% endfor %}
</ul>

<p>
    {% if breeds_count > 0 %}
        <a class="btn btn-primary" href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
        Add a Breed first.
    {% endif %}
</p>

<p>
    <a class="btn btn-secondary" href="{% url 'cats:breed' %}">View breeds</a> ({{ breeds_count }}) | <a
            class="btn btn-secondary" href="{% url 'cats:breed_create' %}">Add a breed</a>
</p>

<p><a href="{% url 'cats:refresh' %}" class="btn btn-primary">Refresh Cats</a></p>
<p><a href="{% url 'home' %}">Back to Apps</a></p>

{% endblock %}