mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_delete'),

    # Path for streaming picture
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    # Paths for comments
    path('ad/<int:pk>/comment/create',
        views.CommentCreateView.as_view(),
        name='comment_create'),
    path('ad/comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(),
        name='comment_delete'),

    # Paths for favorite/ unfavorite
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView
from hello import views as hv

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # admin app
    path('admin/', admin.site.urls),

    # apps home page
    path('', TemplateView.as_view(template_name='home/main.html'), name='home'),

    # Guess Game by Chornenkj
    path('guess/', include('guess.urls')),

    #Ads app to pass DJ4E module on Owned Rows and Users` permittions
    path('ads/', include('ads.urls')),

    # Autos CRUD app to pass course DJ4E module
    # on creating, retreaving, updating and deleting forms
    path('autos/', include('autos.urls')),

    # Cats app to pass course DJ4E module
    # on creating a database
    path('cats/', include('cats.urls')),

    # Unesco app to create database from csv-file
    path('unesco/', include('unesco.urls')),

    # URLs for login and logout
    path('accounts/', include('django.contrib.auth.urls')),

    # these two apps are created just to pass course DJ4E
    path('polls/', include('polls.urls')),
    path('hello/', hv.myview, name='hello'),

    # this is just to browse files in the course DJ4E
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

from taggit.managers import TaggableManager


# Class for Ads
class Ad(models.Model) :

    # Actual data
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()

    # This field is used to check the owner of the data entry
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Ads picture as binary field
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(
        max_length=256,
        null=True,
        blank=True,
        help_text='The MIMEType of the file'
    )

    # Field for comments
    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        related_name='comments_owned'
    )

    # Field for favourites
    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Fav',
        related_name='favorite_ads'
    )

    # Apply tagging to this model
    tags = TaggableManager(blank=True)

    # Date/time of creation and modification - autofields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # String representation of the model
    def __str__(self):
        return self.title


class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.0/ref/models/options/#unique-together
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'ad'], name='unique_together'),
        ]

    def __str__(self) :
        return '{} likes "{}"'.format(self.user.username, self.ad.title[:10])

mysite/ads/forms.py
from django import forms
from .models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize


# Create the form class
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Picture is manual
    class Meta:
        model = Ad
        fields = ['title', 'tags', 'price', 'text', 'picture']

    # Override clean() to validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Override save() to convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        # Make a copy
        f = instance.picture
        # Extract data from the form to the model
        if isinstance(f, InMemoryUploadedFile):
            bytearr = f.read()
            # Read the content type
            instance.content_type = f.content_type
            # Overwrite with the actual image data
            instance.picture = bytearr

        # We save the form data if commit=True
        if commit:
            instance.save()
            # Add to save tags
            self.save_m2m()

        return instance

"""
References for CreateForm:
https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
"""


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(
        required=True,
        max_length=500,
        min_length=3,
        strip=True
    )

mysite/ads/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.db.models import Q
from django.http import HttpResponse

from mysite import settings
from .models import Ad, Comment, Fav
from .owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from .forms import CreateForm, CommentForm
from .utils import dump_queries


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ad_list.html"

    def get(self, request) :

        # Get search value if exists, else False
        strval = request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search

            # Create query to filter by search value case-insensitive
            # Add search in title field
            query = Q(title__icontains=strval)
            # Add search in text field
            query.add(Q(text__icontains=strval), Q.OR)
            # Add search in tags
            query.add(Q(tags__name__in=[strval]), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            # Get 10 most recent Ad objects if no search value
            ad_list = Ad.objects.all().order_by('-updated_at')[:10]

        # Create list of favorites for logged in users
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        # Create context to pass to render a page
        ctx = {
            'ad_list' : ad_list,
            'favorites': favorites,
            'search': strval
        }

        # Code to print queries
        retval = render(request, self.template_name, ctx)
        if settings.DEBUG:
            dump_queries()
        return retval


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk):
        x = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        # Create unbound CreateForm instance to pass to template
        form = CreateForm()
        ctx = {'form': form}
        ctx['edit'] = False
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        # Read form data from the POST data
        form = CreateForm(request.POST, request.FILES or None)

        # If form is not valid return to enter valid data
        # The form will contain previous data from the POST data
        if not form.is_valid():
            ctx = {'form': form}
            ctx['edit'] = False
            return render(request, self.template_name, ctx)

        # If form is valid add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        # And now save data to database
        pic.save()
        form.save_m2m()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        # Get instance with pk passed to create CreateFrom with
        # data from database
        x = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=x)
        ctx = {'form': form}
        ctx['edit'] = True
        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        # Read data from database for pk passed
        x = get_object_or_404(Ad, id=pk, owner=self.request.user)
        # Create form and read data from the POST data for this instance
        form = CreateForm(request.POST, request.FILES or None, instance=x)

        # If form is not valid return to enter valid data
        # The form will contain previous data from the POST data
        if not form.is_valid():
            ctx = {'form': form}
            ctx['edit'] = True
            return render(request, self.template_name, ctx)

        # If form is valid save form data to database
        form.save()
        form.save_m2m()
        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    # By convention:
    # template_name = "ads/ad_confirm_delete.html"


# The view to show picture only
def stream_file(request, pk):
    x = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = x.content_type
    response['Content-Length'] = len(x.picture)
    response.write(x.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # Generate success_url dynamically to return to the ad page
    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}

{% block title %}
Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search
{% endblock %}

{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:all' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

mysite/ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}

{% block title %}
Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search
{% endblock %}

{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}

{% block content %}
{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}

<span style="float: right;">
({{ ad.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>

{% if ad.tags.all %}
<p>Tags:
  {% for tag in ad.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}

{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}

<p>
{{ ad.text }}
</p>

{% if user.is_authenticated %}
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'ads:comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
</form>
</p>
{% endif %}

{% for comment in comments %}
<p>{{ comment.text }} ({{ comment.owner }} | {{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'ads:comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}

<p>
<a href="{% url 'ads:all' %}">All ads</a>
</p>
{% endblock %}

mysite/ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}

{% block title %}
Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
<h1>{% if edit %}Edit{% else %}Create{% endif %} your Ad</h1>

<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
    <input type="submit" class="btn btn-secondary" value="Cancel"
        onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

mysite/ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block title %}
Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search
{% endblock %}

{% block content %}
<h1>Ads List</h1>

<!-- form with search field -->
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<div style="float:right">
<form>
    <input type="text" placeholder="Search..." name="search"
    {% if search %} value="{{ search }}" {% endif %}
    >
    <button type="submit"><i class="fa fa-search"></i></button>
    <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>

<p>
<ul>
    {% for item in ad_list %}
    <li>
        <!-- Row for each ad with name, and Edit and Delete buttons for owners -->
        <a href="{% url 'ads:ad_detail'  item.id %}">{{ item.title }}</a>
        {% if item.owner == user %}
        (<a href="{% url 'ads:ad_update' item.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' item.id %}">Delete</a>)
        {% endif %}

        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <!-- Stars (favorites - for authenticated users only) -->
        {% if user.is_authenticated %}
        <!-- first star - for favourites -->
        <a href="#" onclick=
            "adPost('{% url 'ads:ad_unfavorite' item.id %}', {{ item.id }} ); return false;"
            {% if item.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{item.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second star - for not-favorites -->
        <a href="#" onclick=
             "adPost('{% url 'ads:ad_favorite' item.id %}', {{ item.id }} ); return false;"
            {% if item.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{item.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}

        <!-- brief details for ad -->
        <!-- Ad.text -->
        <div style="left:10px">
            {% if item.text|length < 100 %}
                {{ item.text }}
            {% else %}
                {{ item.text|slice:"0:99" }}
                <a href="{% url 'ads:ad_detail' item.id %}">...</a>
            {% endif %}
        </div>
        <!-- Ad.updated_at -->
        <small>
        {% if item.owner.username %}
            posted by {{ item.owner.username }}
        {% endif %}
        {% load humanize %}
        {{ item.updated_at|naturaltime }}
        </small>
    </li>
    {% empty %}
    <p>There are no articles in the database.</p>
    {% endfor %}
</ul>

</p>
<br/>
<p>
    <a href="{% url 'home' %}">Return to all apps</a>
</p>

<!-- script to send AJAX to create or delete connection between
    Ad and USER_AUTH_MODEL through Fav, and to toggle Fav stars-->
<script>
function adPost(url, ad_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+ad_id).toggle();
        $("#favorite_star_"+ad_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

mysite/ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}

{% block title %}
Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search
{% endblock %}

{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete comment</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}