mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_delete'),

    # Path for streaming picture
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    # Paths for comments
    path('ad/<int:pk>/comment/create',
        views.CommentCreateView.as_view(),
        name='comment_create'),
    path('ad/comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(),
        name='comment_delete'),

    # Paths for favorite/ unfavorite
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'),
]

mysite/autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [
    # App main page and list of Autos
    path('', views.MainView.as_view(), name='all'),

    # Create Auto
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),

    # Update Auto
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),

    # Delete Auto
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),

    # Browse list of Makes
    path('lookup/', views.MakeView.as_view(), name='make_list'),

    # Create Make
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),

    # Update Make
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),

    # Delete Make
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'

urlpatterns = [
    path('', views.CatListView.as_view(), name='all'),
    path('cat/create/', views.CatCreateView.as_view(), name='cat_create'),
    path('cat/<int:pk>/update/', views.CatUpdateView.as_view(), name='cat_update'),
    path('cat/<int:pk>/delete/', views.CatDeleteView.as_view(), name='cat_delete'),

    path('breed/', views.BreedListView.as_view(), name='breed'),
    path('breed/create/', views.BreedCreateView.as_view(), name='breed_create'),
    path('breed/<int:pk>/update/', views.BreedUpdateView.as_view(), name='breed_update'),
    path('breed/<int:pk>/delete/', views.BreedDeleteView.as_view(), name='breed_delete'),

    path('cats_refresh', views.cats_refresh, name='refresh'),
]

mysite/guess/urls.py
from django.urls import path

from . import views

app_name = 'guess'

urlpatterns = [
    path('', views.index, name='index'),
    path('try/', views.TryView.as_view(), name='next_try'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView
from hello import views as hv

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # admin app
    path('admin/', admin.site.urls),

    # apps home page
    path('', TemplateView.as_view(template_name='home/main.html'), name='home'),

    # Guess Game by Chornenkj
    path('guess/', include('guess.urls')),

    #Ads app to pass DJ4E module on Owned Rows and Users` permittions
    path('ads/', include('ads.urls')),

    # Autos CRUD app to pass course DJ4E module
    # on creating, retreaving, updating and deleting forms
    path('autos/', include('autos.urls')),

    # Cats app to pass course DJ4E module
    # on creating a database
    path('cats/', include('cats.urls')),

    # Unesco app to create database from csv-file
    path('unesco/', include('unesco.urls')),

    # URLs for login and logout
    path('accounts/', include('django.contrib.auth.urls')),

    # these two apps are created just to pass course DJ4E
    path('polls/', include('polls.urls')),
    path('hello/', hv.myview, name='hello'),

    # this is just to browse files in the course DJ4E
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'

urlpatterns = [
    path('owner', views.owner, name='owner'),

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/home/views.py
from django.shortcuts import render

# Create your views here.

mysite/home/templates/home/main.html
{% extends 'base_bootstrap.html' %}

{% block title %}
Chornenkj`s Django Projects
{% endblock %}

{% block content %}
    <h1>Welcome to Chornenkj`s Django Projects</h1>

    <p style="font-size: medium">You can view Django codes of this site at
        <a href="https://github.com/chornenkj/university-michigan-django.git">
            Github repository project link</a></p>

    <p style="font-size: medium">You can also view <a href="{% url 'site_path' '' %}"
        target="_blank">working files directory</a></p>

    <p style="font-size: medium">Some apps require user login.<br/>
        So to check these apps functionality, please, use one of the predefined users credentials:<br/>
        <p><ul style="font-size: medium">
            <li>user login: <strong>dj4e_user1</strong>, password: <strong>Meow_f9b784_41</strong></li>
            <li>user login: <strong>dj4e_user2</strong>, password: <strong>Meow_42_f9b784</strong></li>
        </ul></p></p><br/>

<ol style="font-size: large">
    <li><p style="font-size: large"><a href="{% url 'ads:all' %}">Ads CRUD, Users, Pictures, Comments, Favorites, Tags and Search</a></p>
    <p style="font-size: medium">Ads app let you create ads.<br/>
    <em>App functionality includes</em>:</p>
    <ul style="font-size: medium">
    <li>You can create, retrieve, update and delete your ads using your login account.</li>
    <li>You can also browse ads of other users, but you are not allowed to edit or delete them.</li>
    <li>You can add and update pictures for each ad.</li>
    <li>You can comment all ads and delete your comments.</li>
    <li>You can check ads as favorite or unfavorite them (<em>using AJAX</em>).</li>
    <li>You can add tags to each Ad.</li>
    <li>You can search in Ad title and text fields and tags.</li>
    </ul>
    <br></li>

    <li><p style="font-size: large"><a href="{% url 'unesco:index' %}">
        Generate UNESCO Database</a></p>
    <p style="font-size: medium">This app uses script which loads data from csv-file 'unesco.csv'
        and generates an SQLite database of UNESCO sites.<br/>
    <em>This database is separated from the default project database (MySQL)</em>.<br/>
    You can download both files from <a href="{% url 'site_path' 'unesco/' %}"
        target="_blank">this link</a>.</p><br></li>

    <li><p style="font-size: large"><a href="{% url 'guess:index' %}">Guess Game by Chornenkj</a></p>
    <p style="font-size: medium">My game to guess a number.
    Your game is saved to session, so you can continue anytime you like.</p><br></li>

    <li><p style="font-size: large"><a href="{% url 'cats:all' %}">Cats CRUD</a></p>
    <p style="font-size: medium">Cats app let you create Breeds, and create Cats on their base.<br/>
    You can create, retrieve, update and delete data (Breeds and Cats) with this app.<br/>
    Also add a link to <em>python script which refreshes Cats and Breeds database uploading it
    from csv-file</em>.</p><br></li>

    <li><p style="font-size: large"><a href="{% url 'autos:all' %}">Autos CRUD</a></p>
    <p style="font-size: medium">Autos app let you create Makes, and create Autos on their base.<br/>
    You can create, retrieve, update and delete data (Makes and Autos) with this app.</p><br></li>

    <li><p style="font-size: large"><a href="{% url 'polls:index' %}">Polls</a></p>
    <p style="font-size: medium">This app is to vote to the Questions.
    Questions are set in admin app. So you cannot add your ones.</p><br></li>

    <li><p style="font-size: large"><a href="{% url 'hello' %}">Test the session</a></p>
    <p style="font-size: medium">This app just uses session to keep amount of page loads.
    If it is greater than 4, it refreshes.</p><br></li>
</ol>

{% endblock %}